### ISSUE TITLE
about environmental question

### ISSUE THREAD

**Issue by BruceRull** [cuiziteng/Aleth-NeRF#15]
Hi, thank you for your great work. However, the following problems occurred when I configured the environment according to the steps. Could you please tell me how to solve it?

**Comment by cuiziteng** [comment]
This is CUDA error.

Remove the CUDA_VISIBLE_DEVICES=0 and try again.

**Comment by BruceRull** [comment]
I try again, but it doesn't work.

**Comment by cuiziteng** [comment]
https://stackoverflow.com/questions/13654449/error-segmentation-fault-core-dumped

Please check at here ?

<img width="742" alt="image" src="https://github.com/cuiziteng/Aleth-NeRF/assets/55396225/02c4dc07-8344-411c-a228-f6192ef9377e">

**Comment by BruceRull** [comment]
Could you please tell me how much memory this experiment takes up？ I use an a6000 to run this experiment.

**Comment by cuiziteng** [comment]
can you print a nvidia-smi and show photo here?

**Comment by BruceRull** [comment]
![Uploading WI~(9`%AK4Y[]53P54Z@)TT.png…]()

**Comment by BruceRull** [comment]
![WI~(9`%AK4Y 53P54Z@)TT](https://github.com/cuiziteng/Aleth-NeRF/assets/165174674/f4abc1fb-fa8b-4a35-b0a6-fa16ad69e994)

**Comment by cuiziteng** [comment]
Please try smaller batch size and chunk and run again

<img width="326" alt="image" src="https://github.com/cuiziteng/Aleth-NeRF/assets/55396225/eacf920e-1e5e-4783-9af2-59df96c463b5">

**Comment by BruceRull** [comment]
Thank you for your help, I have solved this problem. These packages take up too much memory during training.
![{HGB%D0ZF7B0(J_~ITS{(2R](https://github.com/cuiziteng/Aleth-NeRF/assets/165174674/e5ca980b-474f-482c-84b6-8772b5300151)
